//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpERP.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLedger
    {
        public long LedgerId { get; set; }
        public string LedgerName { get; set; }
        public string Address { get; set; }
        public string AccountNo { get; set; }
        public string PanNo { get; set; }
        public Nullable<System.DateTime> AccOpenDate { get; set; }
        public Nullable<long> SubLedgerId { get; set; }
        public string EmailID { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public Nullable<long> FinancialYearId { get; set; }
        public string MiscCode { get; set; }
        public string IFSCCode { get; set; }
        public string BankBranchName { get; set; }
        public Nullable<bool> Uploaded { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string PinCode { get; set; }
        public string AcType { get; set; }
    }
}
