//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpERP.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrder
    {
        public int PO_Id { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<System.DateTime> PO_Date { get; set; }
        public Nullable<decimal> PO_Amount { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<bool> IsPOComplete { get; set; }
    }
}
