//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpERP.Models.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountTypeDetail
    {
        public int SRNo { get; set; }
        public Nullable<long> AccountTypeId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> SubledgerId { get; set; }
    }
}
