//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpERP.Models.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAllowanceDeduction
    {
        public int AllowDedId { get; set; }
        public string Description { get; set; }
        public int Percentage { get; set; }
        public decimal Amount { get; set; }
        public bool IsPercentage { get; set; }
        public bool IsFixed { get; set; }
        public bool IsFlexible { get; set; }
        public bool IsAllowance { get; set; }
        public bool IsDeduction { get; set; }
        public bool IsBasic { get; set; }
        public bool IsDelete { get; set; }
    }
}
