//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpERP.Models.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int EmpCode { get; set; }
        public string EmpFirstName { get; set; }
        public string EmpMiddleName { get; set; }
        public string EmpLastName { get; set; }
        public string EmpAddress { get; set; }
        public string Password { get; set; }
        public int DeptId { get; set; }
        public Nullable<System.DateTime> EmpDOB { get; set; }
        public Nullable<System.DateTime> EmpDOJ { get; set; }
        public string UserType { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public bool IsDelete { get; set; }
        public string BankName { get; set; }
        public string BankACNo { get; set; }
        public string PFNo { get; set; }
        public string PanNo { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public string EmpEmail { get; set; }
        public Nullable<long> LedgerId { get; set; }
    }
}
