//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpERP.Models.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOpeningBalance
    {
        public long OpeningBalanceId { get; set; }
        public Nullable<long> LedgerId { get; set; }
        public Nullable<System.DateTime> OpeningBalnceEffectFrom { get; set; }
        public Nullable<decimal> CreditBal { get; set; }
        public Nullable<decimal> DebitBal { get; set; }
        public Nullable<long> FinancialYearId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
