//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpERP.Models.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrderDetail
    {
        public int SR_No { get; set; }
        public Nullable<int> PO_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> InvoiceQuantity { get; set; }
    }
}
