//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpERP.Models.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalary
    {
        public int SalId { get; set; }
        public int EmpId { get; set; }
        public System.DateTime SalDate { get; set; }
        public int No_of_Days { get; set; }
        public int LeavesTaken { get; set; }
        public int Attend_Days { get; set; }
        public string Sal_Month { get; set; }
        public decimal NetPayment { get; set; }
        public Nullable<int> OTHours { get; set; }
        public bool IsPaymentDone { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<decimal> OTPayment { get; set; }
    }
}
