//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpERP.Models.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplierMaster
    {
        public int SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string VATCSTNo { get; set; }
        public string ExciseNo { get; set; }
        public string Email { get; set; }
        public string ServiceTaxNo { get; set; }
        public decimal TotalInwardAmnt { get; set; }
        public decimal TotCumInwardAmnt { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string ChangeBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<long> LedgerId { get; set; }
    }
}
