//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpERP.Models.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public long Id { get; set; }
        public Nullable<long> FinancialId { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public Nullable<long> CrLedgerId { get; set; }
        public Nullable<long> DrLedger { get; set; }
        public Nullable<decimal> CrAmount { get; set; }
        public Nullable<decimal> DrAmount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionType { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ByHand { get; set; }
        public string Description { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<bool> IsPostDated { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<int> BillNo { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string DraweeBank { get; set; }
        public Nullable<bool> IsTax { get; set; }
        public Nullable<int> RefBillNo { get; set; }
        public Nullable<bool> IsPartially { get; set; }
        public Nullable<bool> IsChequeReturn { get; set; }
        public Nullable<bool> IsCheequeReturnChargesApplied { get; set; }
        public Nullable<decimal> PartialAmount { get; set; }
    }
}
