//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpERP.Models.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWareHouse
    {
        public long WareHouseNo { get; set; }
        public string WareHouseName { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
